<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>autoPulse</title>
    <link rel="stylesheet " href="<?= asset('css/styles.css') ?>">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inclusive+Sans&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <script src="<?= asset('js/main.js') ?>" defer></script>
</head>

<body class="containerBody">
    <header>
        <div class="containerHeader">
            <a href="/" class="logo">
                <img src="<?= asset('./img/Logo-2.jpg') ?>" width="550px" height="150px" alt="logo">
            </a>
            <nav>
          
                <!-- MENU EN MODE CONNECTE -->
                <?php if (isConnected()) : ?>
                    
                    <a href="<?= buildUrl('logout'); ?>" class=" btn " onclick="ouvrirModal()">
                        <i class="fa-solid fa-right-from-bracket"></i>
                        <p class="spaceNav">
                            Déconnexion
                        </p>
                    </a>
                <?php else : ?>
                    <!-- MENU EN MODE NON CONNECTE -->
                    <a href="/" class="btn">
                        <i class="fa-solid fa-home"></i>
                        <p class="spaceNav">
                            Accueil
                        </p>
                    </a>
                    <a href="<?= buildUrl('signup'); ?>" class=" btn " onclick="ouvrirModal()">
                        <i class="fa-solid fa-user-plus"></i>
                        <p class="spaceNav">
                            Créer un compte
                        </p>
                    </a>

                    <a href="<?= buildUrl('login'); ?>" class=" btn ">
                        <i class="fa-solid fa-right-to-bracket"></i>
                        <p class="spaceNav">
                            Connexion
                        </p>
                    </a>
                <?php endif; ?>
            </nav>
        </div>
    </header>
   <main>
   <?php include '../templates/' . $template . '.phtml'; ?>
   </main>
    <footer>
        <div class="footerBase">
            <div class="footerText">
                <h4>Contactez-nous</h4>
            </div>
            <div class="footerLien">
                <a href="/">00.000.00.00.00</a>
                <a href="/">autopulse@auto.com</a>
            </div>
        </div>
        <div class="footerTexte">
            <div class="footerText">
                <h4>A PROPOS</h4>
            </div>
            <div class="footerLien2">
                <a href="/">Nous rejoindres</a>
                <a href="/">Devenir inspecteur</a>
                <a href="/">F.A.Q</a>
            </div>
        </div>
        </div>
        <!-- <div class="footerBotton">
            <div class="footerIcons">
                <a href="/" class="logoFooter">
                    <img src="<?= asset('./img/facebook.png') ?>" width="50px" height="50px" alt="logo">
                </a>
                <a href="/" class="logoFooter">
                    <img src="<?= asset('./img/instagram.png') ?>" width="50px" height="50px" alt="logo">
                </a>
            </div>
            <div class="footerEnd">
                <p>@autopulse</p>
            </div> -->
    </footer>

</body>

</html>