<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>autoPulse</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inclusive+Sans&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet " href="<?= asset('css/styles.css') ?>">
    <script src="<?= asset('js/main.js') ?>" defer></script>
</head>

<body>
    <header>
        <div class="containerHeader">
            <a href="/" class="logo">
                <img src="<?= asset('./img/Logo-2.jpg') ?>" width="550px" height="150px" alt="logo">
            </a>
            <nav>
                <!-- MENU EN MODE CONNECTE -->
                <?php if (isConnected()) : ?>
                    <!-- Utilisateur avec sous-menu -->
                    <div class="relative group">
                        <details class="group hover:bg-gray-100 hover:text-gray-700 rounded-lg px-4 py-2">
                            <summary class="group flex items-center justify-between">
                                <div class="flex items-center gap-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 opacity-75" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                                    </svg>
                                    <span class="text-sm font-medium">Bonjour <?= $_SESSION['user']['firstname'] . ' ' . $_SESSION['user']['lastname']; ?></span>

                                </div>

                                <span class="shrink-0 transition duration-300 group-open:-rotate-180">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                    </svg>
                                </span>
                            </summary>

                            <ul class="mt-2 space-y-1 px-4">
                                <li>
                                    <a href="<?= buildUrl('logout'); ?>" class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700" onclick="ouvrirModal()">Déconnexion</a>
                                </li>
                                <li>
                                    <a href="<?= buildUrl('notice'); ?>" class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700" onclick="ouvrirModal()">Mes annonces</a>
                                </li>
                                <li>
                                    <a href="<?= buildUrl('placeAnAd'); ?>" class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700" onclick="ouvrirModal()"></a>
                                </li>
                            </ul>
                        </details>
                    </div>

                <?php else : ?>
                    <!-- MENU EN MODE NON CONNECTE -->
                    <a href="/" class="btn">
                        <i class="fa-solid fa-home"></i>
                        <p class="spaceNav">
                            Accueil
                        </p>
                    </a>
                    <a href="<?= buildUrl('signup'); ?>" class=" btn " onclick="ouvrirModal()">
                        <i class="fa-solid fa-user-plus"></i>
                        <p class="spaceNav">
                            Créer un compte
                        </p>
                    </a>

                    <a href="<?= buildUrl('login'); ?>" class=" btn ">
                        <i class="fa-solid fa-right-to-bracket"></i>
                        <p class="spaceNav">
                            Connexion
                        </p>
                    </a>
                <?php endif; ?>
            </nav>
        </div>
    </header>

    <main>
        <?php include '../templates/' . $template . '.phtml'; ?>
    </main>
    <footer>
        <div class="footerBase">
            <div class="footerText">
                <h4>Contactez-nous</h4>
            </div>
            <div class="footerLien">
                <a href="/">00.000.00.00.00</a>
                <a href="/">autopulse@auto.com</a>
            </div>
        </div>
        <div class="footerTexte">
            <div class="footerText">
                <h4>A PROPOS</h4>
            </div>
            <div class="footerLien2">
                <a href="/">Nous rejoindres</a>
                <a href="/">Devenir inspecteur</a>
                <a href="/">F.A.Q</a>
            </div>
        </div>
        </div>
        <!-- <div class="footerBotton">
            <div class="footerIcons">
                <a href="/" class="logoFooter">
                    <img src="<?= asset('./img/facebook.png') ?>" width="50px" height="50px" alt="logo">
                </a>
                <a href="/" class="logoFooter">
                    <img src="<?= asset('./img/instagram.png') ?>" width="50px" height="50px" alt="logo">
                </a>
            </div>
            <div class="footerEnd">
                <p>@autopulse</p>
            </div> -->
    </footer>

</body>

</html>