<div class="max-w-xl mx-auto">
    <!-- Affichage de l'image originalFileName -->

    <!-- Formulaire en utilisant flexbox pour la mise en page -->
    <div class="bg-white p-6 rounded-lg shadow-md my-8">
        <h1 class="text-2xl font-semibold mb-4">Modifier la voiture</h1>
        <form method="POST" action="" enctype="multipart/form-data">
            <div class="w-65 h-65">
                <img src="<?= asset('images/' . $car['originalFileName']) ?>" alt="Image de la voiture" class="w-full h-full object-cover border border-gray-300 rounded-lg">
            </div>

            <div class="mt-2">
                <input type="hidden" name="originalFileName" value="<?= $car['originalFileName'] ?>">
            </div>
            <!-- Champ de téléchargement de fichier pour la nouvelle image -->
            <div class="mt-2 ml-2 flex flex-col items-center justify-items-center">
                <label for="newImage" class="block text-sm font-medium text-gray-700 text-center">Nouvelle image de la voiture</label>
                <input type="file" name="newImage" id="newImage" class="mt-1 p-2 border-gray-300 rounded-md w-full">
            </div>

            <div class="flex flex-wrap -mx-4 mb-4">
                <!-- Marque -->
                <div class="w-1/3 px-4 mb-4">
                    <label for="make" class="block text-sm font-medium text-gray-700 mt-2 text-center">Marque :</label>
                    <p class="text-sm text-gray-500 mt-1 text-center">actuel:</p>
                    <input type="text" id="make" name="make" class="mt-1 p-2 border border-gray-300 rounded-md w-full text-sm text-gray-500 mt-1 focus:outline-none focus:text-gray-900" required value="<?= $car['make'] ?>">
                </div>

                <!-- Carburant -->
                <div class="w-1/3 px-4 mb-4">
                    <label for="fuel" class="block text-sm font-medium text-gray-700 mt-2 text-center">Carburant :</label>
                    <p class="text-sm text-gray-500 mt-1 text-center">actuel :</p>
                    <select id="fuel" name "fuel" class="mt-1 p-2 border border-gray-300 rounded-md w-full text-sm text-gray-500 mt-1 focus:outline-none focus:text-gray-900" required>
                        <option value="essence" <?= ($car['fuel'] === 'essence') ? 'selected' : '' ?>>Essence</option>
                        <option value="diesel" <?= ($car['fuel'] === 'diesel') ? 'selected' : '' ?>>Diesel</option>
                        <option value="hybride" <?= ($car['fuel'] === 'hybride') ? 'selected' : '' ?>>Hybride</option>
                        <option value="electrique" <?= ($car['fuel'] === 'electrique') ? 'selected' : '' ?>>Électrique</option>
                    </select>
                </div>

                <!-- Prix -->
                <div class="w-1/3 px-4 mb-4">
                    <label for="price" class="block text-sm font-medium text-gray-700 mt-2 text-center">Prix :</label>
                    <p class="text-sm text-gray-500 mt-1 text-center">actuel :</p>
                    <input type="number" id="price" name="price" class="mt-1 p-2 border border-gray-300 rounded-md w-full text-sm text-gray-500 mt-1 focus:outline-none focus:text-gray-900" required value="<?= $car['price'] ?>">
                </div>
            </div>
            <div class="flex flex-wrap -mx-4 mb-4">
                <!-- Kilométrage -->
                <div class="w-1/2 px-4 mb-4">
                    <label for="mileage" class="block text-sm font-medium text-gray-700 mt-2 text-center">Kilométrage :</label>
                    <p class="text-sm text-gray-500 mt-1 text-center">actuel:</p>
                    <input type="number" class="vehicleCondition w-full border rounded-md p-2 text-sm text-gray-500 mt-1 focus:outline-none focus:text-gray-900" id="mileage" name="mileage" required value="<?= $car['mileage'] ?>">
                </div>

                <!-- Année -->
                <div class="w-1/2 px-4 mb-4">
                    <label for="years" class="block text-sm font-medium text-gray-700 mt-2 text-center">Année :</label>
                    <p class="text-sm text-gray-500 mt-1 text-center">actuel :</p>
                    <input type="number" class="year w-full border rounded-md p-2 text-sm text-gray-500 mt-1 focus:outline-none focus:text-gray-900" id="years" name="years" min="1990" max="2100" required value="<?= $car['years'] ?>">
                </div>
            </div>

            <!-- Description en bas -->
            <div class="mb-4">
                <label for="accounte" class="block text-sm font-medium text-gray-700 mt-2 text-center">Description :</label>
                <p class="text-sm text-gray-500 mt-1 text-center">actuel :</p>
                <textarea id="accounte" name="accounte" rows="5" cols="25" class="w-full border rounded-md p-2 text-sm text-gray-500 mt-1 focus:outline-none focus:text-gray-900"><?= $car['accounte'] ?></textarea>
            </div>

            <!-- Bouton de soumission -->
            <div class="mt-6 text-center">
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-full">Enregistrer</button>
            </div>
        </form>
    </div>
</div>
