<div id="loginModal" class="modal-container">
        <div class="modal-content">
        <span class="close" id="closeLoginBtn">&times;</span>

            <form action="/login" method="POST">
                <fieldset>
                    <legend>Connexion</legend>
                    <div class="mb-3">
                        <label for="email">Email</label>
                        <input class="form-control" type="email" name="email" id="email">
                    </div>
                    <div class="mb-3">
                        <label for="password">Mot de passe</label>
                        <input class="form-control" type="password" name="password" id="password">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Connexion">
                </fieldset>
            </form>
        </div>
    </div>