<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet " href="<?= asset('css/styles.css') ?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <script src="<?= asset('js/main.js') ?>" defer></script>
</head>

<body class="containerBody">
    <header>
        <div class="containerHeader">
            <a href="/" class="logo">
                <img src="<?= asset('./img/Logo-2.jpg') ?>" width="320px" height="100px" alt="logo">
            </a>

            <nav>
                <a href="/" class="btn">
                    <i class="fa-solid fa-home"></i>
                    Accueil
                </a>

                <!-- MENU EN MODE CONNECTE -->
                <!-- <?php if (isConnected()) : ?>
                    <a href="/logout" class="btn btn-primary mx-1" onclick="ouvrirModal()">
                        <i class="fa-solid fa-right-from-bracket"></i>
                        Déconnexion
                    </a>
                <?php endif; ?> -->
            </nav>

            <!-- inclusion du template spécifique à la page affichée
            <?php include '../templates/' . $template . '.phtml'; ?> -->
    </header>
    <div class="bloc">
        <section class="containerV">
            <div class="position">
                <div class="boxPl">
                    <p>Vendez votre vehicule</p>
                </div>
                <div class="boxPlace">
                    <p class="onglet">Profils</p>
                    <a href="/">Infos</a>
                    <a href="/logout">Deconnexion</a>
                </div>
                <div class="boxPlace">
                    <p class="onglet">Messagerie</p>
                    <a href="/">Nouveaux messages</a>

                </div>
                <div class="boxPlace">

                    <p class="onglet">Documents à fournir</p>
                    <label for="file">Controle Technique :</label>
                    <input type="file" name="file" id="file" accept=".pdf, .doc, .docx">
                    <input type="submit" value="Envoyer">
                </div>
                <div class="boxPlace">

                    <label for="file">Carte grise :</label>
                    <input type="file" name="file" id="file" accept=".pdf, .doc, .docx">
                    <input type="submit" value="Envoyer">

                </div>


            </div>
        </section>
        <aside class="cv">
            ahahahahahha
        </aside>
    </div>
    <footer>
        Footer
    </footer>

</body>

</html>